const { contextBridge, ipcRenderer } = require("electron");
function safeOn(channel, cb) {
  ipcRenderer.removeAllListeners(channel);
  ipcRenderer.on(channel, (_, ...args) => cb(...args));
}
contextBridge.exposeInMainWorld("api", {
  getConfig:        ()       => ipcRenderer.invoke("get-config"),
  saveConfig:       (cfg)    => ipcRenderer.invoke("save-config", cfg),
  sendAction:       (a)      => ipcRenderer.invoke("send-action", a),
  sendAction2:      (a)      => ipcRenderer.invoke("send-action2", a),
  togglePitting:    ()       => ipcRenderer.invoke("toggle-pitting"),
  togglePitting2:   ()       => ipcRenderer.invoke("toggle-pitting2"),
  minimize:         ()       => ipcRenderer.invoke("minimize-app"),
  overlayFitHeight: (h) => ipcRenderer.invoke("overlay:fit-height", h),
  close:            ()       => ipcRenderer.invoke("close-app"),
  toggleTop:        ()       => ipcRenderer.invoke("toggle-top"),
  openDevTools:     ()       => ipcRenderer.invoke("open-devtools"),
  openOAuth:        (url)    => ipcRenderer.invoke("open-oauth", url),
  toggleTimerOverlay: () => ipcRenderer.invoke("overlay:toggle-timer"),
  installUpdate:    ()       => ipcRenderer.invoke("install-update"),
  checkVersion:     ()       => ipcRenderer.invoke("check-version"),
  overlayNudge:      (dx, dy) => ipcRenderer.invoke("overlay:nudge", dx, dy),
overlayResizeBy:   (dw, dh) => ipcRenderer.invoke("overlay:resize-by", dw, dh),
  registerHotkeys:  (kb)     => ipcRenderer.invoke("register-hotkeys", kb),
  suspendHotkeys:   ()       => ipcRenderer.invoke("suspend-hotkeys"),
  toggleSplitView: (enable) => ipcRenderer.invoke("overlay:toggle-split", enable),
  resetOverlayPositions: () => ipcRenderer.invoke("overlay:reset-positions"),
  resumeHotkeys:    ()       => ipcRenderer.invoke("resume-hotkeys"),
  uninstall:        ()       => ipcRenderer.invoke("uninstall"),
  onFuelSourcePickerOpen: (cb) => ipcRenderer.on('fuel-source-picker-open', (_e, sources) => cb(sources)),
selectFuelSource: (id) => ipcRenderer.send('fuel-source-picker-result', id),
  openReleases:     ()       => ipcRenderer.invoke("open-releases"),
  devAuthPassword:  ()       => ipcRenderer.invoke("dev-auth-password"),
  onUpdateAvailable:  (cb) => safeOn("update-available",   cb),
  onUpdateDownloaded: (cb) => safeOn("update-downloaded",  cb),
  onUpdateError:      (cb) => safeOn("update-error",       cb),
  onToast:            (cb) => safeOn("toast",              cb),
  onCooldownStart:    (cb) => safeOn("cooldown-start",     cb),
  onCooldownEnd:      (cb) => safeOn("cooldown-end",       cb),
  installReleaseVersion: (tag) => ipcRenderer.invoke("install-release-version", tag),
  onVersionInstallProgress: (cb) => ipcRenderer.on("version-install-progress", (_e, pct) => cb(pct)),
  onVersionInstallError: (cb) => ipcRenderer.on("version-install-error", (_e, msg) => cb(msg)),
  onPitStateChanged:  (cb) => safeOn("pit-state-changed",  cb),
  onPitStateChanged2: (cb) => safeOn("pit-state-changed2", cb),
  onFlagEvent:        (cb) => safeOn("flag-event",         cb),
  onKeybindFired:     (cb) => safeOn("keybind-fired",      cb),
});
